# DrillingMiner default config.yml

# Set this to true|false to switch if fuel is needed.
requires_fuel: true

# These are the useable fuel wich is used by the DrillingMiner.
fuels:
- coal
- charcoal
- coal_block
- lava_bucket

# The following settings are for the rail placement, number of lines and area design.
dminer_cfg:
  # defines how many normal rails should be placed before a power rail will be placed (default: 7)
  number_of_rails: 7
  # defines how many lines will be builded parallel (default: 1 - max: 3)
  number_of_lines: 1
  # defines the design around the rail line - blockNames can be used, also blockIDs (supports up to 3 different blocks (ACTUALLY ONLY BLOCK1 IS SUPPORTED))
  area_design_block1: stone
  area_design_block2: brick 
  area_design_block3: cobblestone 

# Now we can choose the machine type we want to use to drill through the world.
# Simply set the allowed constructions to true|false to can use them otherwise
# a message will be displayed, if the builded type of machine is not active.
dminer_machine_type: 3x3